const CartActionTypes = {
    TOGGLE_CART_VISIBILITY: 'TOGGLE_CART_VISIBILITY',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    REDUCE_ITEM_QUANTITY_FROM_CART: 'REDUCE_ITEM_QUANTITY_FROM_CART'
  };
  
  export default CartActionTypes;