const collectionActionTypes = {
    GET_COLLECTION: 'GET_COLLECTION',
    UPDATE_COLLECTION_ITEMS: 'UPDATE_COLLECTION_ITEMS',
    FETCHING_COLLECTION_ITEMS: 'FETCHING_COLLECTION_ITEMS',
    FETCHED_COLLECTION_ITEMS: 'FETCHED_COLLECTION_ITEMS',
    FAILED_TO_FETCH_COLLECTION_ITEMS: 'FAILED_TO_FETCH_COLLECTION_ITEMS'
}

export default collectionActionTypes;